# Markdownlint configuration
extends: null
default: true
line-length:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false
ul-style:
  style: dash
no-hard-tabs: false
blanks-around-headings:
  lines_above: 1
  lines_below: 1
blanks-around-lists:
  lines_above: 1
  lines_below: 1
